In [1]:
import numpy as np

#1D array
a = np.array([1,2,3])

print(a)

[1 2 3]


In [2]:
#2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
#3D array
c = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [4]:
#dtype
print(c.dtype)

int64


In [5]:
np.array([1,0,3],dtype = bool)

array([ True, False,  True])

In [6]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
#np.arange
np.arange(1,5)

array([1, 2, 3, 4])

In [8]:
#reshape from 10 to 5x2 RXC

np.arange(1,11).reshape(5,2)

# np.arange(1,13).reshape(5,5)# ValueError: cannot reshape array of size 12 into shape (5,5)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
#np.ones and np.zeros: usecase
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
#np.random
np.random.random((3,4))


array([[0.32929426, 0.80830699, 0.92894503, 0.17734538],
       [0.951448  , 0.20450621, 0.37784205, 0.2212544 ],
       [0.36960179, 0.93050855, 0.8202374 , 0.32500459]])

In [12]:
#np.linspace :given space mei equal dist pe point generate
#UC:
np.linspace(-10,10,10) #(LB,UB,nitems)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [13]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [14]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [15]:
#ndim
a3.ndim

3

In [16]:
#shape :har dim mei kitne items hai
a1.shape


(10,)

In [17]:
a2.shape

(3, 4)

In [18]:
a3.shape

(2, 2, 2)

In [19]:
#size: total no. of items
a3.size


8

In [20]:
#itemsize : har item memory mei kitna size occupy karega

print(a1.itemsize,"Bytes")  #default on colab sabka 8 B hi ayega


8 Bytes


In [21]:
a1 = np.arange(10,dtype=np.int32)
print(a1.itemsize)

#int32 = 4B
#int 64 = 8B by default

4


In [22]:
#dtype: of all items
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing Datatypes

In [23]:
#astype
a3.dtype

dtype('int64')

In [24]:
#use int32 instead :reduce space
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations


In [25]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print("a1 = ",a1)
print("a2 = ",a2)


a1 =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
a2 =  [[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [26]:
#scalar operations: 1 scalar and numpy array

#try arithmetic operations
a2 * 2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [27]:
#relational

a2 >= 19

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [28]:
a2 == 19

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [29]:
#vector operations: 2 numpy arrays

a1 + a2 #same shape only:additn of consecutive arr elem

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

Array functions

In [30]:
a1 = np.random.random((3,3))
a1

array([[0.41403286, 0.52727371, 0.17828321],
       [0.50065168, 0.0205906 , 0.92962187],
       [0.02366613, 0.53356308, 0.15213789]])

In [31]:
a1 = np.round(a1*100)
a1

array([[41., 53., 18.],
       [50.,  2., 93.],
       [ 2., 53., 15.]])

In [32]:
np.max(a1)

np.float64(93.0)

In [33]:
np.min(a1)

np.float64(2.0)

In [34]:
np.sum(a1)

np.float64(327.0)

In [35]:
np.prod(a1)

np.float64(578378718000.0)

In [36]:
#min/max/sum/prod of each row/col
#AXIS : 0 -> col , 1 -> row
np.prod(a1,axis=0)


array([ 4100.,  5618., 25110.])

In [37]:
np.max(a1,axis=1) # max element of each row

array([53., 93., 53.])

In [38]:
np.min(a1,axis=0)

array([ 2.,  2., 15.])

In [39]:
#mean/median/std
np.mean(a1,axis=1)

array([37.33333333, 48.33333333, 23.33333333])

In [40]:
np.median(a1,axis = 1 )

array([41., 50., 15.])

In [41]:
np.std(a1)

np.float64(28.134597128012256)

In [42]:
#trigonometric func

np.sin(a1)

array([[-0.15862267,  0.39592515, -0.75098725],
       [-0.26237485,  0.90929743, -0.94828214],
       [ 0.90929743,  0.39592515,  0.65028784]])

In [43]:
#dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
'''
for dot :
       3x4
       4x3   ,4 should be same
'''
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [44]:
#log and exponents
np.log(a1)

array([[3.71357207, 3.97029191, 2.89037176],
       [3.91202301, 0.69314718, 4.53259949],
       [0.69314718, 3.97029191, 2.7080502 ]])

In [45]:
np.exp(a1)

array([[6.39843494e+17, 1.04137594e+23, 6.56599691e+07],
       [5.18470553e+21, 7.38905610e+00, 2.45124554e+40],
       [7.38905610e+00, 1.04137594e+23, 3.26901737e+06]])

In [46]:
#round/ceil/floor
s = np.random.random((3,3))*100
s

array([[88.02409077, 79.98402344, 15.09696491],
       [ 9.20050288,  3.76218738, 62.62822018],
       [81.38037857, 49.25290043,  5.80257739]])

In [47]:
np.round(s)
#np.round(np.random.random((3,3))*100)

array([[88., 80., 15.],
       [ 9.,  4., 63.],
       [81., 49.,  6.]])

In [48]:
np.ceil(s)

array([[89., 80., 16.],
       [10.,  4., 63.],
       [82., 50.,  6.]])

In [49]:
np.floor(s)

array([[88., 79., 15.],
       [ 9.,  3., 62.],
       [81., 49.,  5.]])

Indexing & Slicing

In [50]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


print("a1 = ",a1)
print()
print("a2 = ",a2)
print()
print("a3 = ",a3)

a1 =  [0 1 2 3 4 5 6 7 8 9]

a2 =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a3 =  [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [51]:
a1[0]

np.int64(0)

In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a2[1,2]   #a2[row,index]

np.int64(6)

In [54]:
a2[1,0]

np.int64(4)

In [55]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [56]:
a3[1,0,1]   #[which 2d array,row,col]

np.int64(5)

In [57]:
a3[0,0,0]

np.int64(0)

In [58]:
a3[1,1,0]

np.int64(6)

In [59]:
#slicing : for multiple items

a1



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a1[2:5]

array([2, 3, 4])

In [61]:
a1[2:5:2]

array([2, 4])

In [62]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
a2[0,:]   # [row,col]
#: for entire row/col

array([0, 1, 2, 3])

In [64]:
a2[:,2]

array([ 2,  6, 10])

In [65]:
a2[1:3,1:3]
#or
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [67]:
#tricky for corner elements
#1:27

a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [72]:
'''1 3
   9 11 '''
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [73]:
''' 4 7 '''
a2[ 1, ::3]

array([4, 7])

In [76]:
'''1 2 3
   5 6 7 '''

a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [77]:
'''1 3
   5 7 '''
a2[0:2,1::2]



array([[1, 3],
       [5, 7]])

In [80]:
#3d

a3 = np.arange(27).reshape(3,3,3)

In [82]:
a3[1]
#or
a3[1,:,: ]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [84]:
#alternate array

a3[::2]


array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [85]:
# 3 4 5
a3[0,1,:]

array([3, 4, 5])

In [87]:
'''
     10
     13
     16
'''

a3[1,:,1]

array([10, 13, 16])

In [88]:
'''
     22  23
     25  26
'''

a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [91]:
#tricky
'''
     0   2
     18  20
'''
a3[::2,0,::2]




array([[ 0,  2],
       [18, 20]])

Iterating


In [92]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
#working on loops
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [98]:
for i in a2:   # 1d arr is printed
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [99]:
for i in a3:   #2d arr is printed
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [100]:
for i in np.nditer(a3):  #each element of 2d array is printed
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


Reshaping

In [101]:
#reshape


In [102]:
#tranpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [103]:
a2.T    #easy syntax

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [106]:
#ravel: any ndim_array into 1d array
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Stacking


In [110]:
#horizontal stacking :join 2/more numpy arrays of same dim
'''ex : if 2x2 & 2x2
hor 2x4 and vert 4x2'''
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [111]:
#vertical stacking
#UC for stacking: diff sources of data
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Splitting

In [113]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
np.hsplit(a4,2)  #(arr,nparts) -> equal parts


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [119]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [116]:
a5 = np.arange(16).reshape(4,4)
a5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
np.vsplit(a5,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [2]:
#check numpy version
import numpy as np
print(np.__version__)

2.4.6
